# R Programming - Week 5 - NPTEL Practice

**Name:** Sheshank Singh <br>
**Roll No.:** 23102A0017 <br>
**Subject:** R Programming <br>
**Week:** 5<br>

## Missing Data Handling

### Missing Data

In [1]:
x = NA
is.na(x)

[1] TRUE

### How to work with missing data

In [2]:
x = c(11, NA, 13, NA)
mean(x)

[1] NA

In [4]:
mean(x, na.rm = TRUE)

[1] 12

### Location of missing values

In [5]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [6]:
which(is.na(x))

[1] 2 4

### Counting number of missing values

In [7]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [8]:
sum(is.na(x))

[1] 2

### Finding complete cased

In [9]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [10]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

### Finding complete data set

In [13]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [15]:
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [16]:
mean(x)

[1] NA

In [17]:
mean(y)

[1] 12

## Conditional Executions -  If and If-Else

### Conditional execution: if()
#### Example 1

In [20]:
x = 5
if(x > 4) x*3

[1] 15

In [21]:
x = 3
if(x > 4) x*3

#### Example 2: Same with using {}

In [22]:
x = 5
x

[1] 5

In [23]:
if(x > 4) {x*3}

[1] 15

In [24]:
x = 3
x

[1] 3

In [25]:
if(x > 4) {x*3}

#### Example 3

In [26]:
x = 6
if(x > 3){
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [28]:
x = 2
if(x > 3){
  print("The value is more than 3")
}

### Conditional Execution: if else()

#### Example 1

In [31]:
x = 5
if(x==3){
  x = x - 1
} else{
  x = 2*x
}
x

[1] 10

#### Example 2

In [34]:
x = 3
if(x==3){
  x = x - 1
} else{
  x = 2*x
}
x

[1] 2

#### Example 3

In [35]:
x = 6
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [36]:
x = 2
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

### Conditional Executions: Nested if else if and if else

#### Example 1

In [37]:
x = 5
if(x == 3){
  x = x - 1
} else if(x < 3){
  x = x+5
} else {x = 2*x}
x

[1] 10

In [38]:
x = 2
if(x == 3){
  x = x - 1
} else if(x < 3){
  x = x+5
} else {x = 2*x}
x

[1] 7

In [39]:
x = 3
if(x == 3){
  x = x - 1
} else if(x < 3){
  x = x+5
} else {x = 2*x}
x

[1] 2

#### Example 4

In [40]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [41]:
ifelse(x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [42]:
x = c(7,9,8,4)
ifelse(x%%2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## Functions for Conditional Executions - switch and which commands

### Switch

#### Example 1

In [43]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [44]:
switch(1, "apple", "banana", "orange")

[1] "apple"

#### Example 2

In [45]:
switch("color", "color" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [46]:
switch("volume", "color" = "blue", "gender" = "male", "volume" = 50)

[1] 50

#### Example 3

In [47]:
switch(4, "apple", "banana", "orange")

In [48]:
switch("size", "color" = "blue", "gender" = "male", "volume" = 50)

### Which

#### Example 1

In [49]:
x = c(10, 15, 8, 14, 6, 12)
x

[1] 10 15  8 14  6 12

In [50]:
which(x == 14)

[1] 4

In [51]:
which(x != 12)

[1] 1 2 3 4 5

In [52]:
which(x > 10)

[1] 2 4 6

#### Example 2

In [54]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [55]:
which.min(x)

[1] 1

In [56]:
which.max(x)

[1] 9

In [57]:
which(x%%2 == 1)

[1] 1 3 5 7 9

In [58]:
which(x%%2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3