# R Programming - Week 9 - NPTEL Practice
**Name:** Sheshank Singh <br>
**Roll No.:** 23102A0017 <br>
**Subject:** R Programming <br>
**Week:** 9 <br>

## Formatting and Display of Strings

In [2]:
print("The zero occur at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occur at", 2 * pi, "radians."): invalid 'quote' argument

In [4]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

### cat functions

In [6]:
cat("The zero occur at", 2*pi, "radians.")

The zero occur at 6.283185 radians.

In [7]:
d = date()
cat("Today's date is:", d)

Today's date is: Tue Sep 22 07:16:50 2026

In [8]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [9]:
cat(x, sep=" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [10]:
cat(x, sep=" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [11]:
x = 7
cat("The square of", x, "is", x^2, "!")

The square of 7 is 49 !

In [12]:
cat("The square root of", x, "is approximately", format(sqrt(x), digits=3))

The square root of 7 is approximately 2.65

In [13]:
evenno = c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [14]:
cat("The first few even numbers are:", evenno)

The first few even numbers are: 2 4 6 8 10

## Paste Function

In [15]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [17]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [18]:
paste("Everybody", "loves", "R Progamming.")

[1] "Everybody loves R Progamming."

In [19]:
paste("Everybody", "loves", "R Progamming.", sep="*")

[1] "Everybody*loves*R Progamming."

In [20]:
paste("Everybody", "loves", "R Progamming.", sep="===")

[1] "Everybody===loves===R Progamming."

In [21]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [25]:
 paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [27]:
 paste(names, "is", "a good", "person.", collapse = ", and ")

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

### Operations with Strings

In [28]:
paste(1, " is first", 2, " is second", 3, " is third", sep="#")

[1] "1# is first#2# is second#3# is third"

In [29]:
paste(1, " is first   ", 2, " is second    ", 3, " is third")

[1] "1  is first    2  is second     3  is third"

In [31]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [32]:
x[1]

[1] "Ex_1"

In [33]:
x[2]

[1] "Ex_2"

In [34]:
x[3]

[1] "Ex_3"

In [35]:
x[4]

[1] "Ex_4"

In [36]:
x[5]

[1] "Ex_5"

In [37]:
x = paste("Ex", 1:5, sep="_", collapse = "")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [38]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [39]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [40]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [41]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

## String Splitting

In [43]:
x = "The&!syntax&!of&!paste&!is!&available!&inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [44]:
strsplit(x, split="!")

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

In [45]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                              "syntax"
[3] "of"                               "paste"
[5] "is!&available!&inthe online-help"

In [48]:
y = strsplit(x, split = "!&")
y

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

#### Notice the access to single components

In [49]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [50]:
y[[1]][2]

[1] "available"

In [51]:
y[[1]][3]

[1] "inthe online-help"

#### Example: Convert to matrix

In [52]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")

In [53]:
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

#### Create matrix of dates and outcome is that the elements are character

In [55]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

#### Create matrix of dates and outcome is that the elements are numbers

In [56]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)

In [57]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [58]:
strsplit("Sheshank",split="")

[[1]]
[1] "S" "h" "e" "s" "h" "a" "n" "k"

## Manipulations with Strings and Alphabets

### Counting characters

In [59]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

In [60]:
nzchar(x)

[1] TRUE

In [61]:
nzchar(y)

[1] TRUE

In [62]:
x = c("Apple", "Banana", "Cake")
x

[1] "Apple"  "Banana" "Cake"

In [63]:
nzchar(x)

[1] TRUE TRUE TRUE

In [64]:
y = c("Apple", "", "Cake")
y

[1] "Apple" ""      "Cake"

In [65]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [66]:
x = c("Apple", "Banana", "Cake")
nchar(x)

[1] 5 6 4

In [67]:
y = c(2, 4, 6)
nchar(y)

[1] 1 1 1

In [68]:
z = c(11, 222, 3333)
nchar(z)

[1] 2 3 4

In [69]:
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 3 4 5

###  Lower and upper cases

In [71]:
x = "R course will start from 24.07.2022"
x

[1] "R course will start from 24.07.2022"

In [72]:
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [73]:
tolower(x)

[1] "r course will start from 24.07.2022"