# R Programming - Week 4 - NPTEL Practice

**Name:** Sheshank Singh <br>
**Roll No.:** 23102A0017 <br>
**Subject:** R Programming <br>
**Week:** 4<br>

Matrix Operation

In [ ]:
x = matrix(nrow=4, ncol=3, data = c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [ ]:
rownames(x) = c("r1","r1","r3","r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r1 2    6    10
r3 3    7    11
r4 4    8    12

In [ ]:
colnames(x) = c("c1","c2","c3")
x

   c1 c2 c3
r1 1  5   9
r1 2  6  10
r3 3  7  11
r4 4  8  12

In [ ]:
x = matrix(nrow=4, ncol=2, data = 2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

Diagonal matrix

In [ ]:
d = diag(1,nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [ ]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Transpose matrix

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

Transpose matrix

In [ ]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
x = matrix(nrow=4, ncol=2, data = c(1:8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
rowSums(x)

[1]  6  8 10 12

In [ ]:
colSums(x)

[1] 10 26

In [ ]:
rowMeans(x)

[1] 3 4 5 6

In [ ]:
colMeans(x)

[1] 2.5 6.5

In [ ]:
x = matrix(nrow=5, ncol=3, byrow=T, data = 1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [ ]:
x[3,]

[1] 7 8 9

In [ ]:
x[,2]

[1]  2  5  8 11 14

In [ ]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [ ]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [ ]:
x-5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [ ]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [ ]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Addition and Subtraction of matrics

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [ ]:
x+y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [ ]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [ ]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [ ]:
x+4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [ ]:
4*x-x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

In [ ]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [ ]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [ ]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
t(x)%*%x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
x%*%t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [ ]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

In [ ]:
rbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [ ]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [ ]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))

In [ ]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [ ]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [ ]:
x = 8
(x < 10) || (x < 2)

[1] TRUE

In [ ]:
x = 18
(x < 10) || (x < 2)

[1] FALSE

In [ ]:
x = c(8,18)
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [ ]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [ ]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

In [ ]:
(x < 10) & (x <2)

[1] FALSE FALSE

In [ ]:
x = 1:6
(x>2) & (x<5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [ ]:
x[(x>2) & (x < 5)]

[1] 3 4

In [ ]:
x = TRUE

In [ ]:
y = FALSE

In [ ]:
x&y

[1] FALSE

In [ ]:
x|y

[1] TRUE

In [ ]:
!x

[1] FALSE

In [ ]:
x = 5

In [ ]:
logical1 = (x>2)

In [ ]:
logical1

[1] TRUE

In [ ]:
logical2 = (x < 10)

In [ ]:
logical2

[1] TRUE

In [ ]:
logical3 = (x!=5)

In [ ]:
logical3

[1] FALSE

In [ ]:
logical4 = (2*x > 11)

In [ ]:
logical4

[1] FALSE

In [ ]:
is.logical(logical4)

[1] TRUE

In [ ]:
logical5 = (3*x < 20)

In [ ]:
logical5

[1] TRUE

In [ ]:
is.logical(logical5)

[1] TRUE

In [ ]:
8 > 7

[1] TRUE

In [ ]:
7 < 5

[1] FALSE

In [ ]:
7 > 7

[1] FALSE

In [ ]:
7 >= 7

[1] TRUE

In [ ]:
8 < 8

[1] FALSE

In [ ]:
8 <= 8

[1] TRUE

In [ ]:
8 != 9

[1] TRUE

In [ ]:
9 != 9

[1] FALSE

In [ ]:
7 == 7

[1] TRUE

In [ ]:
7 == 8

[1] FALSE

In [ ]:
x = TRUE

In [ ]:
!x

[1] FALSE

In [ ]:
x = c(1, 2, 3)
y = c(4, 5, 6)

In [ ]:
x > y

[1] FALSE FALSE FALSE

In [ ]:
x < y

[1] TRUE TRUE TRUE

In [ ]:
x != y

[1] TRUE TRUE TRUE

In [ ]:
x == y

[1] FALSE FALSE FALSE

In [ ]:
isTRUE(8 < 6)

[1] FALSE

In [ ]:
isTRUE(8 > 6)

[1] TRUE

In [ ]:
isFALSE(5 < 8)

[1] FALSE

In [ ]:
isFALSE(5 > 8)

[1] TRUE